from datetime import datetime

from src.constants.delivery_status import DeliveryStatus
from src.constants.states import State
from src.constants.utah_cities import UtahCity
from src.models.package import Package

# project_packages = [
#     Package(package_id=1, address='195 W Oakland Ave', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84115, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=21, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=2, address='2530 S 500 E', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84106, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=44, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=3, address='233 Canyon Rd', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84103, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=2, status=DeliveryStatus.AT_HUB, special_note='Can only be on truck 2'),
#     Package(package_id=4, address='380 W 2880 S', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84115, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=4, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=5, address='410 S State St', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84111, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=5, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=6, address='3060 Lester St', city=UtahCities.WEST_VALLEY_CITY, state=State.UTAH, zip_code=84119, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=88, status=DeliveryStatus.AT_HUB, special_note='Delayed on flight---will not arrive to depot until 9:05 am'),
#     Package(package_id=7, address='1330 2100 S', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84106, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=8, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=8, address='300 State St', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84103, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=9, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=9, address='300 State St', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84103, is_verified_address=False, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=2, status=DeliveryStatus.AT_HUB, special_note='Wrong address listed'),
#     Package(package_id=10, address='600 E 900 South', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84105, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=1, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=11, address='2600 Taylorsville Blvd', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84118, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=1, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=12, address='3575 W Valley Central Station bus Loop', city=UtahCities.WEST_VALLEY_CITY, state=State.UTAH, zip_code=84119, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=1, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=13, address='2010 W 500 S', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84104, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=2, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=14, address='4300 S 1300 E', city=UtahCities.MILLCREEK, state=State.UTAH, zip_code=84117, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=88, status=DeliveryStatus.AT_HUB, special_note='Must be delivered with 15, 19'),
#     Package(package_id=15, address='4580 S 2300 E', city=UtahCities.HOLLADAY, state=State.UTAH, zip_code=84117, is_verified_address=True, deadline=datetime.strptime('09:00:00', '%I:%M:%S'), weight=4, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=16, address='4580 S 2300 E', city=UtahCities.HOLLADAY, state=State.UTAH, zip_code=84117, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=88, status=DeliveryStatus.AT_HUB, special_note='Must be delivered with 13, 19'),
#     Package(package_id=17, address='3148 S 1100 W', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84119, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=2, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=18, address='1488 4800 S', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84123, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=6, status=DeliveryStatus.AT_HUB, special_note='Can only be on truck 2'),
#     Package(package_id=19, address='177 W Price Ave', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84115, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=37, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=20, address='3595 Main St', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84115, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=37, status=DeliveryStatus.AT_HUB, special_note='Must be delivered with 13, 15'),
#     Package(package_id=21, address='3595 Main St', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84115, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=3, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=22, address='6351 South 900 East', city=UtahCities.MURRAY, state=State.UTAH, zip_code=84121, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=2, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=23, address='5100 South 2700 West', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84118, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=5, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=24, address='5025 State St', city=UtahCities.MURRAY, state=State.UTAH, zip_code=84107, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=7, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=25, address='5383 South 900 East #104', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84117, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=7, status=DeliveryStatus.AT_HUB, special_note='Delayed on flight---will not arrive to depot until 9:05 am'),
#     Package(package_id=26, address='5383 South 900 East #104', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84117, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=25, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=27, address='1060 Dalton Ave S', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84104, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=5, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=28, address='2835 Main St', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84115, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=7, status=DeliveryStatus.AT_HUB, special_note='Delayed on flight---will not arrive to depot until 9:05 am'),
#     Package(package_id=29, address='1330 2100 S', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84106, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=2, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=30, address='300 State St', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84103, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=1, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=31, address='3365 S 900 W', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84119, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=1, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=32, address='3365 S 900 W', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84119, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=1, status=DeliveryStatus.AT_HUB, special_note='Delayed on flight---will not arrive to depot until 9:05 am'),
#     Package(package_id=33, address='2530 S 500 E', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84106, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=1, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=34, address='4580 S 2300 E', city=UtahCities.HOLLADAY, state=State.UTAH, zip_code=84117, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=2, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=35, address='1060 Dalton Ave S', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84104, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=88, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=36, address='2300 Parkway Blvd', city=UtahCities.WEST_VALLEY_CITY, state=State.UTAH, zip_code=84119, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=88, status=DeliveryStatus.AT_HUB, special_note='Can only be on truck 2'),
#     Package(package_id=37, address='410 S State St', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84111, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=2, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=38, address='410 S State St', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84111, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=9, status=DeliveryStatus.AT_HUB, special_note='Can only be on truck 2'),
#     Package(package_id=39, address='2010 W 500 S', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84104, is_verified_address=True, deadline=datetime.strptime('19:00:00', '%I:%M:%S'), weight=9, status=DeliveryStatus.AT_HUB, special_note=''),
#     Package(package_id=40, address='380 W 2880 S', city=UtahCities.SALT_LAKE_CITY, state=State.UTAH, zip_code=84115, is_verified_address=True, deadline=datetime.strptime('10:30:00', '%I:%M:%S'), weight=45, status=DeliveryStatus.AT_HUB, special_note='')
# ]
